# This is a basic workflow to help you get started with Actions

name: Sealos Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "**sealos-install.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sealos:
    runs-on: ubuntu-latest

    steps:
      - name: Echo infos
        run: |
          hostname
          ip addr
          which docker || true
          free -m
          
      - name: Remove docker
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get purge docker-ce docker-ce-cli containerd.io # docker-compose-plugin
          sudo rm -rf /var/lib/docker
          sudo rm -rf /var/lib/containerd
          sudo apt-get remove -y moby-engine moby-cli moby-buildx moby-compose

      - name: Install sealos
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/labring/ /" | sudo tee /etc/apt/sources.list.d/labring.list
          sudo apt update
          sudo apt install sealos
          sudo sealos version
          
      - name: Install kubernetes
        run: |
          #sudo -u root sealos run labring/kubernetes:v1.22.10  labring/calico:v3.22.1 --single
          sudo -u root sealos run labring/kubernetes:v1.24.0  labring/calico:v3.24.1 --single

      - name: Wait 30s for ready
        run: |
          sleep 40s
          sudo kubectl get nodes
          
      - name: Wait 30s for get pods
        run: |
          sleep 30s
          sudo kubectl get nodes
          sudo kubectl get pods -A
          
      - name: Trace memory
        run: free -m
